/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_futronictech_AnsiSDKLib */

#ifndef _Included_com_futronictech_AnsiSDKLib
#define _Included_com_futronictech_AnsiSDKLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_futronictech_AnsiSDKLib
 * Method:    OpenDevice
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_futronictech_AnsiSDKLib_OpenDevice
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_futronictech_AnsiSDKLib
 * Method:    OpenDeviceCtx
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_futronictech_AnsiSDKLib_OpenDeviceCtx
  (JNIEnv *, jobject, jobject );

/*
 * Class:     com_futronictech_AnsiSDKLib
 * Method:    CloseDevice
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_futronictech_AnsiSDKLib_CloseDevice
  (JNIEnv *, jobject);

/*
 * Class:     com_futronictech_AnsiSDKLib
 * Method:    GetImageSize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_futronictech_AnsiSDKLib_FillImageSize
  (JNIEnv *, jobject);

/*
 * Class:     com_futronictech_AnsiSDKLib
 * Method:    IsFingerPresent
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_futronictech_AnsiSDKLib_IsFingerPresent
  (JNIEnv *, jobject);

/*
 * Class:     com_futronictech_AnsiSDKLib
 * Method:    CaptureImage
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_futronictech_AnsiSDKLib_CaptureImage
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_futronictech_AnsiSDKLib
 * Method:    CreateTemplate
 * Signature: (I[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_futronictech_AnsiSDKLib_CreateTemplate
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray, jintArray);

/*
 * Class:     com_futronictech_AnsiSDKLib
 * Method:    VerifyTemplate
 * Signature: (I[B[B[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_futronictech_AnsiSDKLib_VerifyTemplate
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray,jfloatArray);

/*
 * Class:     com_futronictech_AnsiSDKLib
 * Method:    MatchTemplates
 * Signature: ([B[B[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_futronictech_AnsiSDKLib_MatchTemplates
  (JNIEnv *, jobject, jbyteArray, jbyteArray,jfloatArray);

/*
 * Class:     com_futronictech_AnsiSDKLib
 * Method:    ConvertAnsiTemplateToIso
 * Signature: ([B[B[I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_futronictech_AnsiSDKLib_ConvertAnsiTemplateToIso
  (JNIEnv *, jobject, jbyteArray, jbyteArray,jintArray);

/*
 * Class:     com_futronictech_AnsiSDKLib
 * Method:    GetMaxTemplateSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_futronictech_AnsiSDKLib_GetMaxTemplateSize();

#ifdef __cplusplus
}
#endif
#endif
